In [ ]:
import numpy as np
a=np.arange(10,51,2)
print(f'even numbers are {a}')

even numbers are [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
a1=np.linspace(0,1,9)
print(a1)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [ ]:
a2=np.full((5,5),1)
a2[1:4,1:4]=0
print(a2)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#retail sales performance
import numpy as np
stores=np.array(["store_A","store_B","store_c","store_d","store_e"])
sales=np.array([ [120000,135000,142000,155000],[98000,105000,110000,108000],[150000,148000,160000,172000],[87000,92000,99000,115000],[130000,138000,141000,149000]])
print(f'totalsales for every store : {sales.sum(axis=1)}')
print(f'averagequarterlysales for every store : {sales.mean(axis=1)}')
print(f'totalsales for every quarter : {sales.sum(axis=0)}')
totalsales=sales.sum(axis=1)
i=np.argmax(totalsales)
print(f'highest annualsales : {stores[i]}')
j=np.argsort(totalsales)[::-1]
print(f'rank highest to lowest : {stores[j]}')
overallaverage=np.mean(totalsales)
print(overallaverage)
flaggedstores=stores[totalsales>overallaverage]
print(f'flag stores ={flaggedstores}')
change=(np.diff(sales,axis=1)/sales[:,:-1])*100
print(f'quarter overquarter change = {np.round(change,2)}')



totalsales for every store : [552000 421000 630000 393000 558000]
averagequarterlysales for every store : [138000. 105250. 157500.  98250. 139500.]
totalsales for every quarter : [585000 618000 652000 699000]
highest annualsales : store_c
rank highest to lowest : ['store_c' 'store_e' 'store_A' 'store_B' 'store_d']
510800.0
flag stores =['store_A' 'store_c' 'store_e']
quarter overquarter change = [[12.5   5.19  9.15]
 [ 7.14  4.76 -1.82]
 [-1.33  8.11  7.5 ]
 [ 5.75  7.61 16.16]
 [ 6.15  2.17  5.67]]


In [ ]:
# student performance analytics

In [ ]:
students=np.array(["anu","binu","cathy","deepa","ebin","fahad"])
marks=np.array([[82,75,91,88],[61,68,70,65],[45,52,48,55],[90,94,89,92],[72,80,76,85],[38,42,49,44]])
subjects=np.array(["python","sql","excel","statistics"])

In [ ]:
totalmarks=np.sum(marks,axis=1)
print(f'totalmarks : {totalmarks}')
saveragemarks=np.mean(marks,axis=1)
print(f'averagemarks : {saveragemarks}')
print(f'{students} :{totalmarks}')

totalmarks : [336 264 200 365 313 173]
averagemarks : [84.   66.   50.   91.25 78.25 43.25]
['anu' 'binu' 'cathy' 'deepa' 'ebin' 'fahad'] :[336 264 200 365 313 173]


In [ ]:
averagemarks=np.mean(marks,axis=0)
print(f'averagemarks for subject : {averagemarks}')

averagemarks for subject : [64.66666667 68.5        70.5        71.5       ]


In [ ]:
i=np.max(marks,axis=0)
print(i)


[90 94 91 92]


In [ ]:
i=np.where(marks>=50,"pass","fail")
print(f'{students} : marks : {i}')

['anu' 'binu' 'cathy' 'deepa' 'ebin' 'fahad'] : marks : [['pass' 'pass' 'pass' 'pass']
 ['pass' 'pass' 'pass' 'pass']
 ['fail' 'pass' 'fail' 'pass']
 ['pass' 'pass' 'pass' 'pass']
 ['pass' 'pass' 'pass' 'pass']
 ['fail' 'fail' 'fail' 'fail']]


In [ ]:
below_60_students=students[saveragemarks<60]
print(below_60_students)

['cathy' 'fahad']


In [ ]:
conditions=[marks>=80,marks>=60,marks>=50]
choice=["A","B","C"]
grade=np.select(conditions,choice,default="F")
print(grade)

[['A' 'B' 'A' 'A']
 ['B' 'B' 'B' 'B']
 ['F' 'C' 'F' 'C']
 ['A' 'A' 'A' 'A']
 ['B' 'A' 'B' 'A']
 ['F' 'F' 'F' 'F']]


In [ ]:
# employee performance and salary analytics

In [ ]:
emp = ["Arun", "Bhavana", "Charan", "Divya", "Eshan", "Fathima"]
perfor = np.array([
    [78, 82, 85, 88],
    [65, 70, 68, 74],
    [92, 89, 95, 91],
    [55, 62, 60, 67],
    [81, 79, 84, 87],
    [72, 75, 78, 80]
])
quarters = ["Q1", "Q2", "Q3", "Q4"]
print(emp)

['Arun', 'Bhavana', 'Charan', 'Divya', 'Eshan', 'Fathima']


In [ ]:
#total performance
total_perfor=np.sum(perfor,axis=1)
print(total_perfor)

[333 277 367 244 331 305]


In [ ]:
#average quaterly performace for every employee
average=np.mean(perfor,axis=1)
print(f'Average : ',average)

Average :  [83.25 69.25 91.75 61.   82.75 76.25]


In [ ]:
#averageperformance for each quarter
qaverage=np.mean(perfor,axis=0)
print(f'Average quarter: ',qaverage)

Average quarter:  [73.83333333 76.16666667 78.33333333 81.16666667]


In [ ]:
#employee with highest total performance
h=np.argmax(total_perfor)
print(f'highest total performance is {emp[h]}')


highest total performance is Charan


In [ ]:
#rank all employee
r=np.argsort(total_perfor[::-1])
for i in r:
 print(emp[i],":",total_perfor[i])

Charan : 367
Eshan : 331
Arun : 333
Bhavana : 277
Fathima : 305
Divya : 244


In [ ]:
#percentage growth
growth=np.diff(perfor,axis=1)/perfor[:,:-1]*100
print("Growth:",np.round(growth, 2))

Growth: [[ 5.13  3.66  3.53]
 [ 7.69 -2.86  8.82]
 [-3.26  6.74 -4.21]
 [12.73 -3.23 11.67]
 [-2.47  6.33  3.57]
 [ 4.17  4.    2.56]]


In [ ]:
#avg equal or less than 80
print("avg equal or less than 80 :",np.array(emp)[average>=80])

avg equal or less than 80 : ['Arun' 'Charan' 'Eshan']


In [ ]:
print(f'no of employee have average below 70 : {np.size(average[average<70])}')

no of employee have average below 70 : 2


In [ ]:
#highest performance
print(np.max(perfor))

95


In [ ]:
#employee and quater where highest score
row,col= np.unravel_index(np.argmax(perfor), perfor.shape)

print("Employee:", emp[row])
print("Quarter:", quarters[col])

Employee: Charan
Quarter: Q3
