In [ ]:
import numpy as np
a=np.arange(10,51,2)
print(f'even numbers are {a}')

even numbers are [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
a1=np.linspace(0,1,9)
print(a1)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [ ]:
a2=np.full((5,5),1)
a2[1:4,1:4]=0
print(a2)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [23]:
import numpy as np
stores=np.array(["store_A","store_B","store_c","store_d","store_e"])
sales=np.array([ [120000,135000,142000,155000],[98000,105000,110000,108000],[150000,148000,160000,172000],[87000,92000,99000,115000],[130000,138000,141000,149000]])
print(f'totalsales for every store : {sales.sum(axis=1)}')
print(f'averagequarterlysales for every store : {sales.mean(axis=1)}')
print(f'totalsales for every quarter : {sales.sum(axis=0)}')
totalsales=sales.sum(axis=1)
i=np.argmax(totalsales)
print(f'highest annualsales : {stores[i]}')
j=np.argsort(totalsales)[::-1]
print(f'rank highest to lowest : {stores[j]}')
overallaverage=np.mean(totalsales)
print(overallaverage)
flaggedstores=stores[totalsales>overallaverage]
print(f'flag stores ={flaggedstores}')




totalsales for every store : [552000 421000 630000 393000 558000]
averagequarterlysales for every store : [138000. 105250. 157500.  98250. 139500.]
totalsales for every quarter : [585000 618000 652000 699000]
highest annualsales : store_c
rank highest to lowest : ['store_c' 'store_e' 'store_A' 'store_B' 'store_d']
510800.0
flag stores =['store_A' 'store_c' 'store_e']


In [25]:
students=np.array(["anu","binu","cathy","deepa","ebin","fahad"])
marks=np.array([[82,75,91,88],[61,68,70,65],[45,52,48,55],[90,94,89,92],[72,80,76,85],[38,42,49,44]])
subjects=np.array(["python","sql","excel","statistics"])

In [71]:
totalmarks=np.sum(marks,axis=1)
print(f'totalmarks : {totalmarks}')
saveragemarks=np.mean(marks,axis=1)
print(f'averagemarks : {saveragemarks}')
print(f'{students} :{totalmarks}')

totalmarks : [336 264 200 365 313 173]
averagemarks : [84.   66.   50.   91.25 78.25 43.25]
['anu' 'binu' 'cathy' 'deepa' 'ebin' 'fahad'] :[336 264 200 365 313 173]


In [43]:
averagemarks=np.mean(marks,axis=0)
print(f'averagemarks for subject : {averagemarks}')

averagemarks for subject : [64.66666667 68.5        70.5        71.5       ]


In [55]:
i=np.max(marks,axis=0)
print(i)


[90 94 91 92]


In [59]:
i=np.where(marks>=50,"pass","fail")
print(f'{students} : marks : {i}')

['anu' 'binu' 'cathy' 'deepa' 'ebin' 'fahad'] : marks : [['pass' 'pass' 'pass' 'pass']
 ['pass' 'pass' 'pass' 'pass']
 ['fail' 'pass' 'fail' 'pass']
 ['pass' 'pass' 'pass' 'pass']
 ['pass' 'pass' 'pass' 'pass']
 ['fail' 'fail' 'fail' 'fail']]


In [79]:
below_60_students=students[saveragemarks<60]
print(below_60_students)

['cathy' 'fahad']
